### ISSUE TITLE
How to deal with 'the ucldMean stateNode was absent in BEAST v2.4'?

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci/babette#103]
From Sylvia:

[...]

I'm using a script for generating xml files for multiples loci to run beast on each of these genes. That script loads the library 'babette' and had been applied several times without any problems. Now the log file gives the following error which probably arises from the `babette` package:

```
Error in beautier::create_ucld_mean_state_node_param_xml(inference_model) :
The ucldMean stateNode was absent in BEAST v2.4
Calls: create_beast2_input_file ... eval_bare -> <Anonymous> -> <Anonymous> -> <Anonymous>
Execution halted
```

Can you tell me whether something has been modified in the babette package that may cause a bug?

[...]

**Comment by richelbilderbeek** [comment]
Hi Sylvia,

Thanks for the fun question!

You appear to use a feature that is absent in the default BEAUti version (which is v2.4).

To use v2.6, where the feature is supported:

```r
beauti_options <- beautier::create_beauti_options_v2_6()
```

Then plug it into a function that has a `beauti_options` as an argument. Most likely it is `beautier::create_inference_model` that you use, hence this will become:

```r
inference_model <- beautier::create_inference_model(
  # your things here,
  beauti_options = beauti_options
)
```

If that does not work, let me know. Especially a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be useful.

Cheers, Richel

**Comment by mmatschiner** [comment]
Hi Richel,

Thanks for your help! Sylvia had run into this issue while trying to establish a pipeline that I had recommended to her. I was also not sure what the issue was, because I was quite certain that the same script had worked as it was at some point earlier. For completeness, here's what we had tried to do: We had an R script named `make_xml.r` with the following content:

```
# Load the babette library.
library("babette")

# Get the command-line arguments.
args <- commandArgs(trailingOnly = TRUE)
fasta <- args[1]
xml <- args[2]

# Define a site model based on the hky model.
site_model <- create_hky_site_model()

# Define a relaxed clock model.
clock_model <- create_rln_clock_model()

# Define a constraint on the age of the root.
mrca_prior <- create_mrca_prior(
   taxa_names = get_taxa_names(fasta),
   mrca_distr = create_normal_distr(mean = 1, sigma = 0.001),
   name = "all"
)

# Specify a run length of 500,000 iterations.
mcmc <-  create_mcmc(chain_length = 5000000)

# Make an xml file with babette.
create_beast2_input_file(
    fasta,
    xml,
    site_model = site_model,
    clock_model = clock_model,
    mrca_prior = mrca_prior,
    mcmc = mcmc
)
```

We executed the script with a command like `Rscript make_xml.r NAME.fasta NAME.xml`
As I said, I think this used to work at some point, but now didn't anymore. I'm not sure, why.

But your solution helps. Adding `beauti_options <- beautier::create_beauti_options_v2_6()` before calling `create_beast2_input_file` and then adding `beauti_options = beauti_options` when calling `create_beast2_input_file` fixes the issue.

Cheers,
Michael
