### ISSUE TITLE
Feature request: intermediate output

### ISSUE THREAD

**Issue by thijsjanzen** [ropensci/babette#66]
I love to see whether something is running, how far it is, and how much longer I still need to wait.
BEAST2 by default outputs a line that summarizes the current state, and also the time spent per 1M trees, as shown here: https://taming-the-beast.org/tutorials/Introduction-to-BEAST2/figures/beast_out.png.

Although the 'VERBOSE' option adds some extra output within R, it does not generate intermediate output like this. Would it be possible to also include this type of output, or to add an extra flag for this?

**Comment by richelbilderbeek** [comment]
Thanks for this request!

Sadly, I have no idea how to do this: I use `system2` to call BEAST2, but *its* intermediate output is only displayed when the run in finished. If there is a way to directly show that output, this Issue is as good as fixed. 

If you (or anyone) knows a way how to let `system2` show its intermediate output, I will happily add it. Ducking :duck:, however, failed.

 * If not, I will unhappily close this Issue.
 * If yes, I'll fix this within a week :+1:

**Comment by richelbilderbeek** [comment]
Unhappily closing this Issue :slightly_frowning_face:
